services:
  backend-node:
    container_name: backend-node #pour accéder au conteneur par lien depuis un autre conteneur sans problème
    build:
      context: .
      target: backend_node
    expose:
    - "80"
    restart: on-failure
    env_file:
      - .env
    user: backend_node
    volumes:
      - ./backend:/app
      - backend_modules:/app/node_modules #pour pas écraser les résultats du npm install du dockerfile quand je monte le volume /app
    depends_on:
      - bd_mongo
  react:
    container_name: react
    build:
      context: .
      target: react
    expose:
      - "3000"
    depends_on:
      - backend-node
    env_file:
      - .env
    restart: on-failure
    user: react
    volumes:
      - ./frontend:/app
      - react_modules:/app/node_modules
      - react_build:/app/build
  bd_mongo:
    container_name: bd_mongo
    image: mongo:latest
    expose: 
      - "27017"
    env_file:
      - .env
    user: mongodb
    restart: on-failure
    volumes:
      - mongo:/data/db #mongo stocke ses données dans data/db, utile pour pas que les données soient supprimés si on supprime le conteneur

  nginx:
    build:
      context: .
      target: web_nginx
    ports:
      - "80:80"
      - "3000:80" #pour le hot reloading de react qui est sur le port 3000
    depends_on:
      - backend-node
    volumes:
     - ./nginx/media:/app/media
    
volumes:
  mongo: #lire explication dans volume bd_mongo, ici c'est pour que docker gère tout seul le volume
  react_modules:
  react_build:
  backend_modules:
