services:
  backend-node:
    container_name: backend-node #pour accéder au conteneur par lien depuis un autre conteneur sans problème
    build:
      context: .
      target: backend_node
    image: backend-node:latest
    expose:
    - "80"
    restart: on-failure
    env_file:
      - .env
    user: backend_node
    volumes:
      - ./backend:/app
      - backend_modules:/app/node_modules #pour pas écraser les résultats du npm install du dockerfile quand je monte le volume /app
    depends_on:
      - bd-mongo
    networks:
      - nginx-backend
      - backend-bd
  react:
    container_name: react
    build:
      context: .
      target: react
    image: react:latest
    expose:
      - "3000"
    depends_on:
      - backend-node
    env_file:
      - .env
    restart: on-failure
    user: react
    volumes:
      - ./frontend:/app
      - /app/node_modules

      - react_build:/app/build
    networks:
      - nginx-frontend
  bd-mongo:
    container_name: bd-mongo
    image: mongo:latest
    expose: 
      - "27017"
    env_file:
      - .env
    user: mongodb
    restart: on-failure
    volumes:
      - mongo:/data/db #mongo stocke ses données dans data/db, utile pour pas que les données soient supprimés si on supprime le conteneur
    networks:
      - backend-bd
  nginx:
    build:
      context: .
      target: web_nginx
    image: nginx-de:latest
    ports:
      - "80:80"
      - "3000:80" #pour le hot reloading de react qui est sur le port 3000
    depends_on:
      - backend-node
    volumes:
     - ./nginx/media:/app/media
     - react_build:/app/build
    networks:
      - nginx-backend
      - nginx-frontend
volumes:
  mongo: #lire explication dans volume bd-mongo, ici c'est pour que docker gère tout seul le volume
  react_build:
  backend_modules:

networks:
  backend-bd:
    driver: bridge
    name: backend-bd
    ipam:
      config:
        - subnet: 192.168.1.0/29 #docker voulait pas me laisser créer de /30, askip il utilise une ip pour lui (autre que l'adresse réseau et broadcast)
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "false"
      com.docker.network.bridge.enable_gateway: "false"

  nginx-backend:
    driver: bridge
    name : nginx-backend
    ipam:
      config:
        - subnet: 192.168.1.8/29
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "false"
      com.docker.network.bridge.enable_gateway: "false"

  nginx-frontend:
    driver: bridge
    name: nginx-frontend
    ipam:
      config:
      - subnet: 192.168.1.16/29
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "false"
      com.docker.network.bridge.enable_gateway: "false"