apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |
{{ tpl (.Files.Get "files/default.conf") . | indent 4 }}
