apiVersion: app/v1
kind: Deployment
metadata:
    name: {{.Release.Name}}--nginx
spec:
    replicas: {{ .Values.services.nginx.replicas }}
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
                - name: nginx
                image: {{ .Values.services.nginx.image }} 
                ports: 
                    - containerPort: {{ .Values.services.app.port }}
                resources:
                    {{- toYaml .Values.services.nginx.resources | nindent 6 }}