apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-back
  namespace: {{ .Release.Namespace }} #helm install monchart . --namespace DE pour spécifier le namespace et .Release.Name=monchart ici
spec:
  replicas: {{ .Values.services.back.replicas }}
  selector:
    matchLabels:
      app: {{ include "monchart.name" . }}
      component: back
  template:
    metadata:
      labels:
        app: {{ include "monchart.name" . }}
        component: back
    spec:
      initContainers:
      - name: wait-for-mongo
        image: busybox:latest
        command: ['sh', '-c', 'until nc -zv de-driving-enhanced-mongo 27017; do echo "waiting for mongo"; sleep 2; done']
      containers:
      - name: back
        image: {{ .Values.services.back.image }} 
        ports: 
        - containerPort: {{ .Values.services.back.port }}
        resources:
          {{- toYaml .Values.services.back.resources | nindent 10 }}