apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monchart.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.services.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ include "monchart.name" . }}
      component: frontend
  template:
    metadata:
      labels:
        app: {{ include "monchart.name" . }}
        component: frontend
    spec:
      volumes:
      -   name: react-static
          emptyDir: {}
      -   name: nginx-config
          configMap:
            name: {{ .Release.Name }}-nginx-config
      -   name: media-volume
          persistentVolumeClaim:
            claimName: media-pvc
      containers:
      -   name: react-builder
          image: {{ .Values.services.frontend.reactImage }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              npm install && npm run build && sleep 3600
          workingDir: /app
          volumeMounts:
            - name: react-static
              mountPath: {{ .Values.services.frontend.sharedVolume.mountPath }}
      -   name: nginx
          image: {{ .Values.services.frontend.nginxImage }}
          ports:
            - containerPort: 80
          volumeMounts:
          -   name: react-static
              mountPath: {{ .Values.services.frontend.sharedVolume.mountPath }}
          -   name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf