apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{.Release.Name}}-bd-mongo
    namespace: {{ .Release.Namespace }}
spec:
    replicas: {{ .Values.services.bd_mongo.replicas }}
    selector:
        matchLabels:
            app: {{ include "monchart.name" . }}
            component: bd-mongo
    template:
        metadata:
            labels:
                app: {{ include "monchart.name" . }}
                component: bd-mongo
                
        spec:
            containers:
            -   name: bd-mongo
                image: {{ .Values.services.bd_mongo.image }} 
                ports: 
                -   containerPort: {{ .Values.services.bd_mongo.port }}
                envFrom:
                -   secretRef:
                        name: mongo-secret
                resources:
                    {{- toYaml .Values.services.bd_mongo.resources | nindent 16 }}
                volumeMounts:
                -   name: mongo-data
                    mountPath: /data/db
            volumes:
            -   name: mongo-data
                persistentVolumeClaim:
                    claimName: {{ include "monchart.fullname" . }}-mongo-pvc