apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{.Release.Name}}-back
    namespace: {{ .Release.Namespace }} #helm install monchart . --namespace DE pour spécifier le namespace et .Release.Name=monchart ici
spec:
    replicas: {{ .Values.services.back.replicas }}
    selector:
        matchLabels:
            app: back
    template:
        metadata:
            labels:
                app: {{ include "monchart.name" . }}
                component: back
        spec:
            containers:
            - name: back
                image: {{ .Values.services.back.image }} 
                ports: 
                    - containerPort: {{ .Values.services.back.port }}
                resources:
                    {{- toYaml .Values.services.back.resources | nindent 16 }}