apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "monchart.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    #traefik.ingress.kubernetes.io/router.middlewares: default@kubernetescrd pour mettre un middleware
spec:
  rules:
    - host: {{ .Values.services.frontend.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "monchart.fullname" . }}--frontend
                port:
                  number: {{ .Values.services.frontend.port }}
