apiVersion: batch/v1
kind: Job
metadata:
  name: media-init
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      volumes:
      - name: media-volume
        persistentVolumeClaim:
          claimName: media-pvc
      - name: nginx-media-volume
        hostPath:
          path: /nginx/media
      containers:
      - name: media-init
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          mkdir -p /mnt/media/image
          echo "Initialisation des fichiers media..."
          
          # Copie des fichiers depuis /nginx/media vers le volume persistant
          if [ -d "/src/nginx/media" ]; then
            echo "Copie des fichiers depuis /src/nginx/media..."
            cp -r /src/nginx/media/* /mnt/media/
          else
            echo "Le répertoire source /src/nginx/media n'existe pas"
          fi
          
          # Vérification des fichiers copiés
          echo "Contenu du répertoire destination:"
          ls -la /mnt/media/
          
          echo "Files initialized successfully"
        volumeMounts:
        - name: media-volume
          mountPath: /mnt/media
        - name: nginx-media-volume
          mountPath: /src/nginx/media
          readOnly: true
      restartPolicy: Never
  backoffLimit: 4