apiVersion: v1
kind: Service
metadata:
    name: {{ include  "monchart.fullname" . }}-mongo
    namespace: {{ .Release.Namespace }}
    labels:
        app: {{ include "monchart.name" . }}
        chart: {{ include "monchart.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
spec:
    type: {{ .Values.services.bd_mongo.type }}
    ports: 
    -   port: {{ .Values.services.bd_mongo.port }}
        targetPort: {{ .Values.services.bd_mongo.targetPort }}
        protocol: TCP
        name: http
    selector:
        app: {{ include "monchart.name" . }}
        component: bd_mongo