apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Namespace }}-stripprefix
  namespace: {{ .Release.Namespace }}
spec:
  replacePathRegex:
    regex: "^/api/(.*)"
    replacement: "/$1"
