services:
  frontend:
    domain: de-test.duckdns.org
    reactImage: react:latest
    nginxImage: nginx-de:latest
    replicas: 1
    type: ClusterIP
    sharedVolume:
      mountPath: /app/build
    port: 80
    targetPort: 80
    resources:
      limits:
        cpu: "500m" #1 demi coeur max
        memory: "500Mi"
      requests:
        cpu: "250m"
        memory: "128Mi"

  back:
    image: backend-node:latest
    port: 80
    targetPort: 80
    replicas: 1
    type: ClusterIP
    resources:
      limits: 
        cpu: "1" #un coeur max
        memory: "500Mi"
      requests:
        cpu: "500m"
        memory: "256Mi"
    
  
  bd_mongo:
    image: mongo:latest
    port: 27017
    targetPort: 27017
    replicas: 1
    type: ClusterIP
    storage:
      enabled: true
      size: 1Gi
    resources:
      limits: 
        cpu: "1" #un coeur max
        memory: "500Mi"
      requests:
        cpu: "500m"
        memory: "256Mi"
      
